<a href="https://colab.research.google.com/github/eloelo5057/kurs_AI/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import pandas as pd
import numpy as np
print(pd.__version__)

2.2.2

1. `Series` - pojedyncza kolumna danych w pandas (Można myśleć o niej jak o jednej kolumnie w Excelu)
2. `DataFrame` - cała tabela danych (Można myśleć o nim jak o arkuszu Excela albo tabeli złożonej z wielu kolumn)
3. `NaN` - brak danych (Not a Number - ale w pandas używa się go ogólnie jako oznaczenia pustej/brakującej wartości)

In [50]:
mydata = {
    "michał": 8,
    "lena": 9,
    "adam": 67,
    "piotr": 67
}
s = pd.Series(mydata)
print(s)

michał     8
lena       9
adam      67
piotr     67
dtype: int64

In [51]:
s = pd.Series([18, 17, 19, 20, "kot"], index=["Kuba", "Kasia", "Wojtek", "Adam", "Tomek"])
print(s)

print(f"rozmiar: {s.size}")
print(f"kształt: {s.shape}")
print(f"typ danych: {s.dtype}")
print(f"indexy: {s.index}")
print(f"wartości: {s.values}")
print(f"wartość dla konkretnego indexu: {s["Wojtek"]}")
print(f"wartość dla elementu na pozycji 1: {s.iloc[1]}")

Kuba       18
Kasia      17
Wojtek     19
Adam       20
Tomek     kot
dtype: object
rozmiar: 5
kształt: (5,)
typ danych: object
indexy: Index(['Kuba', 'Kasia', 'Wojtek', 'Adam', 'Tomek'], dtype='object')
wartości: [18 17 19 20 'kot']
wartość dla konkretnego indexu: 19
wartość dla elementu na pozycji 1: 17

In [52]:
import pandas as pd

data = {
    "ceny": [15, 20, 17],
    "Ilość": [50, 60, 40]
}
df = pd.DataFrame(data, index=["dzien1", "dzien2", "dzien3"])
print(df)

        ceny  Ilość
dzien1    15     50
dzien2    20     60
dzien3    17     40

In [53]:
print(df.loc["dzien2"])

ceny     20
Ilość    60
Name: dzien2, dtype: int64

In [54]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, dzien1 to dzien3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ceny    3 non-null      int64
 1   Ilość   3 non-null      int64
dtypes: int64(2)
memory usage: 180.0+ bytes
None

**Mini projekt - analiza danych Gigathonu**

`Założenia` - W analizowanym etapie konkursu brało udział 25 osób które
rozwiązywały zadania. Do zdobycia było maksymalnie 120 punktów. Nie
wszystkie osoby nadesłały prace konkursowe - nie posiadają one przypisanej
punktacji.

[PLIK](https://docs.google.com/spreadsheets/d/1mF209JYrFKZm_ASJ5qcm_BzDSd6JhAz4/edit?gid=442052669#gid=442052669)

Twoim zadaniem jest:
1. Wczytaj dane z pliku Gigathon_Wyniki.xlsx udostępnionego przez
trenera
2. Wyświetl zawartość pliku jako dataframe
3. Wyświetl 5 pierwszych, a następnie 5 ostatnich wpisów w pliku
4. Dodaj kolumnę “Wynik procentowy” która będzie zawierała informację o
wyniku przeliczonym na punkty.
5. Przefiltruj listę uczestników tak, aby zostały tylko osoby które nadesłały
zadania konkursowe
6. Posortuj uczestników od najlepszego wyniku do najsłabszego
7. Dodanie kolumny zakwalifikowany, w której przypisana zostanie
wartość True dla osób które uzyskały ponad 70% możliwych do
uzyskania punktów, reszta osób powinna mieć przypisaną wartość
False
8. Przygotuj zestawienie które pogrupuje uczestników względem
zakwalifikowania się do kolejnego etapu i wieku. Dla każdej grupy zlicz
ile osób mieści się w tym przedziale, jaki był najniższy i największy
wynik w danym przedziale, oraz jaka była średnia i mediana.
9. Rozbij tabelę na dwie mniejsze tabele - zakwalifikowani oraz
niezakwalifikowani. Zapisz je do oddzielnych plików .xlsx

`Niech każdy punkt wykonany zostanie w nowej sekcji kodu`

In [55]:
import pandas as pd

df = pd.read_excel("/content/Gigathon_Wyniki.xlsx")

In [56]:
df

         Imię  Wiek  Punktacja
0      Łukasz    18       51.0
1   Magdalena    18       52.0
2    Radosław    15       46.0
3      Patryk    15       52.0
4        Anna    14      110.0
5     Dagmara    16        NaN
6      Tomasz    16      112.0
7    Weronika    17      104.0
8     Nikodem    17       97.0
9      Bartek    14        NaN
10      Jakub    16       61.0
11   Gabriela    16       92.0
12     Hubert    15      120.0
13    Zuzanna    13       70.0
14     Oliwia    14       84.0
15      Filip    16      100.0
16    Ewelina    17       98.0
17   Karolina    14       63.0
18     Xawery    17       39.0
19     Cezary    13        NaN
20        Iga    15       77.0
21    Urszula    14      102.0
22        Jan    17      102.0
23     Michał    15        NaN
24  Katarzyna    18       68.0

In [57]:
print(df.head(5))
print("\n")
print(df.tail(5))

        Imię  Wiek  Punktacja
0     Łukasz    18       51.0
1  Magdalena    18       52.0
2   Radosław    15       46.0
3     Patryk    15       52.0
4       Anna    14      110.0


         Imię  Wiek  Punktacja
20        Iga    15       77.0
21    Urszula    14      102.0
22        Jan    17      102.0
23     Michał    15        NaN
24  Katarzyna    18       68.0

In [58]:
df['Wynik procentowy'] = df["Punktacja"]/120*100
df

         Imię  Wiek  Punktacja  Wynik procentowy
0      Łukasz    18       51.0         42.500000
1   Magdalena    18       52.0         43.333333
2    Radosław    15       46.0         38.333333
3      Patryk    15       52.0         43.333333
4        Anna    14      110.0         91.666667
5     Dagmara    16        NaN               NaN
6      Tomasz    16      112.0         93.333333
7    Weronika    17      104.0         86.666667
8     Nikodem    17       97.0         80.833333
9      Bartek    14        NaN               NaN
10      Jakub    16       61.0         50.833333
11   Gabriela    16       92.0         76.666667
12     Hubert    15      120.0        100.000000
13    Zuzanna    13       70.0         58.333333
14     Oliwia    14       84.0         70.000000
15      Filip    16      100.0         83.333333
16    Ewelina    17       98.0         81.666667
17   Karolina    14       63.0         52.500000
18     Xawery    17       39.0         32.500000
19     Cezary    13        NaN               NaN
20        Iga    15       77.0         64.166667
21    Urszula    14      102.0         85.000000
22        Jan    17      102.0         85.000000
23     Michał    15        NaN               NaN
24  Katarzyna    18       68.0         56.666667

In [59]:
# Do usunięcia rekordów z wartością NaN służy metoda .dropna().
# Parametr inplace informuje że usuwamy dane z oryginalnego
# dataframe, domyślnie metoda zwraca kopię dataframe z usuniętymi
# rekordami.
df.dropna(inplace=True)
df

         Imię  Wiek  Punktacja  Wynik procentowy
0      Łukasz    18       51.0         42.500000
1   Magdalena    18       52.0         43.333333
2    Radosław    15       46.0         38.333333
3      Patryk    15       52.0         43.333333
4        Anna    14      110.0         91.666667
6      Tomasz    16      112.0         93.333333
7    Weronika    17      104.0         86.666667
8     Nikodem    17       97.0         80.833333
10      Jakub    16       61.0         50.833333
11   Gabriela    16       92.0         76.666667
12     Hubert    15      120.0        100.000000
13    Zuzanna    13       70.0         58.333333
14     Oliwia    14       84.0         70.000000
15      Filip    16      100.0         83.333333
16    Ewelina    17       98.0         81.666667
17   Karolina    14       63.0         52.500000
18     Xawery    17       39.0         32.500000
20        Iga    15       77.0         64.166667
21    Urszula    14      102.0         85.000000
22        Jan    17      102.0         85.000000
24  Katarzyna    18       68.0         56.666667

In [60]:
# Do sortowania wartości służy metoda .sort_values().
# Parametry:
# 'by' - według której kolumny odbywa się sortowanie,
# 'ascending' - kolejność sortowania (rosnąca lub malejąca).
df.sort_values(by="Punktacja", ascending=False, inplace=True)
df

         Imię  Wiek  Punktacja  Wynik procentowy
12     Hubert    15      120.0        100.000000
6      Tomasz    16      112.0         93.333333
4        Anna    14      110.0         91.666667
7    Weronika    17      104.0         86.666667
22        Jan    17      102.0         85.000000
21    Urszula    14      102.0         85.000000
15      Filip    16      100.0         83.333333
16    Ewelina    17       98.0         81.666667
8     Nikodem    17       97.0         80.833333
11   Gabriela    16       92.0         76.666667
14     Oliwia    14       84.0         70.000000
20        Iga    15       77.0         64.166667
13    Zuzanna    13       70.0         58.333333
24  Katarzyna    18       68.0         56.666667
17   Karolina    14       63.0         52.500000
10      Jakub    16       61.0         50.833333
3      Patryk    15       52.0         43.333333
1   Magdalena    18       52.0         43.333333
0      Łukasz    18       51.0         42.500000
2    Radosław    15       46.0         38.333333
18     Xawery    17       39.0         32.500000

In [61]:
df["Zakwalifikowany"] = df["Wynik procentowy"]>70
df

         Imię  Wiek  Punktacja  Wynik procentowy  Zakwalifikowany
12     Hubert    15      120.0        100.000000             True
6      Tomasz    16      112.0         93.333333             True
4        Anna    14      110.0         91.666667             True
7    Weronika    17      104.0         86.666667             True
22        Jan    17      102.0         85.000000             True
21    Urszula    14      102.0         85.000000             True
15      Filip    16      100.0         83.333333             True
16    Ewelina    17       98.0         81.666667             True
8     Nikodem    17       97.0         80.833333             True
11   Gabriela    16       92.0         76.666667             True
14     Oliwia    14       84.0         70.000000            False
20        Iga    15       77.0         64.166667            False
13    Zuzanna    13       70.0         58.333333            False
24  Katarzyna    18       68.0         56.666667            False
17   Karolina    14       63.0         52.500000            False
10      Jakub    16       61.0         50.833333            False
3      Patryk    15       52.0         43.333333            False
1   Magdalena    18       52.0         43.333333            False
0      Łukasz    18       51.0         42.500000            False
2    Radosław    15       46.0         38.333333            False
18     Xawery    17       39.0         32.500000            False

In [63]:
df.groupby(["Zakwalifikowany", "Wiek"])[["Punktacja", "Wynik procentowy"]].agg(["count", "min", "max", "mean", "median"])

                     Punktacja                                   \
                         count    min    max        mean median
Zakwalifikowany Wiek
False           13           1   70.0   70.0   70.000000   70.0
                14           2   63.0   84.0   73.500000   73.5
                15           3   46.0   77.0   58.333333   52.0
                16           1   61.0   61.0   61.000000   61.0
                17           1   39.0   39.0   39.000000   39.0
                18           3   51.0   68.0   57.000000   52.0
True            14           2  102.0  110.0  106.000000  106.0
                15           1  120.0  120.0  120.000000  120.0
                16           3   92.0  112.0  101.333333  100.0
                17           4   97.0  104.0  100.250000  100.0

                     Wynik procentowy                                      \
                                count         min         max        mean
Zakwalifikowany Wiek
False           13                  1   58.333333   58.333333   58.333333
                14                  2   52.500000   70.000000   61.250000
                15                  3   38.333333   64.166667   48.611111
                16                  1   50.833333   50.833333   50.833333
                17                  1   32.500000   32.500000   32.500000
                18                  3   42.500000   56.666667   47.500000
True            14                  2   85.000000   91.666667   88.333333
                15                  1  100.000000  100.000000  100.000000
                16                  3   76.666667   93.333333   84.444444
                17                  4   80.833333   86.666667   83.541667


                          median
Zakwalifikowany Wiek
False           13     58.333333
                14     61.250000
                15     43.333333
                16     50.833333
                17     32.500000
                18     43.333333
True            14     88.333333
                15    100.000000
                16     83.333333
                17     83.333333